### ISSUE TITLE
MyWeekly

### ISSUE THREAD

**Issue by YongseopKim** [YongseopKim/ONE-vscode#7]
Weekly

**Comment by YongseopKim** [comment]
# W10

## 0307(월)

### 무엇을 했나?

무엇을 할지에 대해서 구체적으로 생각했고, 일의 순서를 생각.

### 무엇을 할것인가?

- [x] 이것에 대해서 이슈로 올리고, 진행할 생각. 그 전에 여러분들의 의견을 들을려고.
  - UI와 별개로 Tests 들을 통해서 내부를 어느정구 구현할 수 있을것이라 예상
  - 설치 -> COMPILE -> EXECUTE -> VALUE_TEST
  - 설치: docker image -> local/ssh/sdb 관련 구현 -> PackageManager
  - COMPILE: CompileManager
  - EXECUTE: ExecuteManager, IO tool, ...
  - VALUE_TET: diff tool, ...

----------------------------------------------------------------------------------

## 3/08(화)

### 무엇을 했나?

- 회의
- 이슈 생성

### 무엇을 할것인가?

- [x] ONE-vscode 설명회 계획 및 준비
- [ ] ssh 관련해서 조사

----------------------------------------------------------------------------------

## 3/09(수) - 공휴일 대선

----------------------------------------------------------------------------------

## 3/10(목)

### 무엇을 했나?

- ONE-vscode 코드 분석 ppt
- 이슈 생성
  - 기존에 처리해야할 문제
  - one-cmd -> onecc
  - 껏다 켜야 하는 문제

### 무엇을 할것인가?

- [ ] ssh 관련해서 조사
- [x] unittest 코드 추가하기

----------------------------------------------------------------------------------

TASK, SPRINT에 등록

**Comment by YongseopKim** [comment]
# W11

월
화 unittest draft 완성
수 ~~push 시작~~, compile 일 계획, 
목 daily-meeting, onecmd->onecc, init jobs
금 MBO 완료

**Comment by YongseopKim** [comment]
# SPRINT

mbo...

unittest -> ci
- 일단, 가능한가?
- 가능 -> 드래프트
- 불가능 -> unittest 발라내는 드래프트

compile 부분 정리 시작
- onecc cmd
- 각 cmd 별 options
- 공유
- arrange options

ssh 부분
- ssh client command
- draft: module ts + unittest

## W13 3/28(월)~4/1(금)

- [x] unittest -> ci 우선 되는지 체크 -> draft
- [x] onecc cmd + compile option 리스팅 -> 의견 듣기
- [ ] ssh command 공부 후 module draft
- [x] MBO 완료
- [x] CompileEnv, ExecutionEnv data structure 그리기

### OTHERS

- [ ] npm script -> os independent : https://www.npmjs.com/package/run-script-os
- [x] `윤재님 draft`
- [x] 릴리즈 일정 이슈

### TODO

## W14 4/4(월)~4/8(금)

- [x] Project/릴리즈 정리
- [x] MBO 완료
- [x] ssh command 공부 후 module draft

project task assign
달마다 릴리즈 담당자

### OTHERS

- [ ] npm script -> os independent : https://www.npmjs.com/package/run-script-os

**Comment by YongseopKim** [comment]
# SPRINT

- [x] unit test ci 완료
- [x] compile 부분의 대략 스케줄은 짬...
- [x] ssh module draft
    - password 저장 방식
    - sudo 처리
    - share?
- [x] ONE-vscode/project
    - asignee가 issue는 우선 만들자
    - compile panel 누가?

4/22(금)~5/13(금) BR 교육

## W15 4/11~15

- toolset api <- ssh module
    - compile toolset api
        - 4/11(월) 계획 세우기
        - 4/15(금) design 및 draft(impl+test)
        - 4/22(금) 완료
    - execute toolset api
        - 4/11(월) 계획 세우기
        - 4/15(금) design 및 draft(impl+test)
        - 4/22(금) 완료
- execute/value-test
    - 4/11(월) 계획 세우기
    - 4/15(금) design 및 draft(impl+test)
    - 4/22(금) 완료
- 세미나: ts/js
    - 4/18(월) 발표
- 세미나: ssh
    - 4/14(목) 발표

## W16 4/18~22

**Comment by YongseopKim** [comment]
# others
- [ ] npm script -> os independent : https://www.npmjs.com/package/run-script-os

**Comment by YongseopKim** [comment]
# SPRINT
## W17 4/25~4/29

- [ ] TCM Score
- [ ] PRs soon

src/Backend.ts - global backend + src/extension.ts
src/Backend/API.ts - interface Backend
src/Backend/Compiler.ts
src/Backend/Executor.ts : this should be more investigated but can be pushed as an interface
src/Backend/Toolchain.ts + DebianToolchain + Toolchains -> as class not interface
src/Project/Command.ts + Version.ts -> src/Backend/
src/Project/Job.ts + JobConfig + JobToolchain
src/Project/JobRunner + ToolRunner
(These PRs should be included with own tests!)

## W18 5/02~5/06

**Comment by YongseopKim** [comment]
# SPRINT

## W20 5/16~20

- [x] 5/16/월 연차
- [ ] Default Compile Option Plan
- [ ] UI Review를 어떻게 해야할까? 
- [ ] UI Test 자동화를 어떻게 해야할까?
- [ ] Public과 Private에서 동시에 진행되어야만 하는 작업들을 어떻게 해야할까?
- [ ] 이슈 만들기


### 5/19(목)

목요일 회의에서 언급할 것
- [ ] PR 리뷰 문화 - 현재 어떤 상태인가? 만족하는가? 무엇에 만족하고, 무엇에 불만족하는가?
- [ ] UI - Review

## W21 5/23~27

**Comment by YongseopKim** [comment]
# SPRINT

## W25 6/20~24

- [x] ~20/월 device draft & pr 보기
- [x] ~21/화 인터뷰 대비
- [ ] ~21/화 Default Compile Option New Plan
- [ ] ~21/화 SQ - 결과 뽑기
- [ ] ~22/수 user study - guide 작성 (ONE-vscode and TRIV-vscode)
- [ ] 23/목~ 교육: 6/23,24,27
- [ ] UserStudy 관련 미션 수행
- [ ] refactoring for BR, Plan it
- [ ] 기득님: draft 통합/ui
- [x] sprint 다시 보기
- [x] user study
- [x] do device together

## W26 6/27~7/1

- [ ] 교육: 6/23,24,27
